name: CI Pipelines

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Run tests with coverage
        run: npm test -- --coverage

      - name: Run Prettier Check
        run: npm run prettier-check

      - name: Publish package
        if: ${{ github.token != '' }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
